import Link from "next/link";

import { getEventFeed, getPublicEvent } from "@/features/events/queries";
import { CopyLinkButton } from "@/features/events/components/copy-link-button";

export default async function EventDetailPage({ params }: { params: Promise<{ eventSlug: string }> }) {
  const { eventSlug } = await params;
  const event = await getPublicEvent(eventSlug);
  const posts = await getEventFeed(String(event.id));
  return <main className="mx-auto min-h-screen max-w-4xl px-5 py-8"><div className="flex items-center justify-between"><Link className="text-sm text-emerald-700" href="/feed">← 홈 피드</Link><CopyLinkButton /></div><header className="mt-6 grid gap-8 md:grid-cols-[280px_1fr]"><div className="aspect-[1/1.414] rounded-xl bg-zinc-200 bg-cover bg-center" style={event.poster_image_url ? { backgroundImage: `url(${String(event.poster_image_url)})` } : undefined} /><div><p className="text-sm font-medium text-emerald-700">{String(event.organization_name)}</p><h1 className="mt-2 text-3xl font-semibold">{String(event.title)}</h1><dl className="mt-6 space-y-2 text-sm text-zinc-700"><div><dt className="inline text-zinc-500">일시 </dt><dd className="inline">{new Date(String(event.event_start_at)).toLocaleString("ko-KR")}</dd></div><div><dt className="inline text-zinc-500">장소 </dt><dd className="inline">{String(event.venue)}</dd></div><div><dt className="inline text-zinc-500">가격 </dt><dd className="inline">{Number(event.ticket_price).toLocaleString("ko-KR")}원</dd></div><div><dt className="inline text-zinc-500">잔여 </dt><dd className="inline">{Number(event.remaining_count)}석/매</dd></div></dl><Link className="mt-8 inline-flex rounded-lg bg-emerald-700 px-5 py-3 font-medium text-white" href={`/events/${eventSlug}/reserve`}>{Number(event.remaining_count) > 0 ? "예매하기" : "매진"}</Link></div></header><section className="mt-12 border-t border-zinc-200 pt-8"><h2 className="text-xl font-semibold">공연 소개</h2><p className="mt-4 whitespace-pre-wrap leading-7 text-zinc-700">{String(event.description)}</p></section><section className="mt-12"><h2 className="text-xl font-semibold">공연 피드</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">{posts.map((post) => <article className="overflow-hidden rounded-xl border border-zinc-200 bg-white" key={String(post.id)}><div className="aspect-square bg-zinc-100 bg-cover bg-center" style={{ backgroundImage: `url(${String(post.image_url)})` }} /><p className="whitespace-pre-wrap p-4 text-sm leading-6">{String(post.content)}</p></article>)}</div></section><section className="mt-12 rounded-xl bg-zinc-100 p-6 text-sm"><h2 className="font-semibold">예매 및 취소 안내</h2><p className="mt-2">최대 {Number(event.max_tickets_per_person)}매 · 취소 마감 {new Date(String(event.cancel_deadline_at)).toLocaleString("ko-KR")}</p></section></main>;
}
